apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default storageclass will be set
  volumeName: ebs-static # Volumne name means Persistent volume 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
