kind: Service
apiVersion: v1
metadata:
  name: nginx
spec: 
  selector:
    project: expense
    component: backend
    environment: dev
    version: "1.0.0"
  ports:
    - protocol: TCP
      port: 80 #service port
      target port: 80
---
kind: Pod
apiVersion: v1
metadata:
  name: labels
  labels:
    project: expense
    component: backend
    environment: dev
    version: "1.0.0"
spec:
  containers:
    - name: nginx
      image: nginx